### ISSUE TITLE
Some words are not colored

### ISSUE THREAD

**Issue by kocsis1david** [PolyMeilex/vscode-wgsl#4]
Types like `vecX<>` are not colored, also in the parameter list, everything has the same color.

It would be nice if types were recognized if they are pascal case, like `VertexOutput`.

![image](https://user-images.githubusercontent.com/722066/126028166-ea3d76c5-cfe7-498e-bf35-3e355aaded07.png)

**Comment by PolyMeilex** [comment]
`vscode-wgsl` does recognize `vecX` and `matXxY`
![img](https://i.imgur.com/2yGlk6O.png)
It's just cheapens that many themes color it as white. That being said, I will change its type to be something with higher chance of being colored. (probably something like `storage.type`)

> also in the parameter list, everything has the same color.

yeah, it's super annoying, I haven't found a reason for this behavior yet.

> It would be nice if types were recognized if they are pascal case, like VertexOutput.

That's a grate idea, should be easy to add too.

**Comment by PolyMeilex** [comment]
I published `0.1.10` version, I believe it addressed all of your problems, give it a try and let me know if it works as you would expect.

**Comment by kocsis1david** [comment]
That was fast, looks better now. But the return value is still not colored.

**Comment by PolyMeilex** [comment]
Ok, now it should work, instead of trying to patch it I rewrote the whole thing with the newest `WGSL` spec in mind. Let's hope that I did not introduce to many regressions by doing that.
